apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app.kubernetes.io/name: echo-server
  name: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - image: echoserver:0.0.2
        name: echo-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: portal
spec:
  containers:
  - image: nginx
    name: nginx
    
