apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: fortune
  name: fortune
---
apiVersion: v1
kind: Namespace
metadata:
  name: fortune
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app.kubernetes.io/name: front
  name: front
  namespace: fortune
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front
    spec:
      containers:
      - image: fortune-front:dev
        name: front
        ports:
        - containerPort: 8080
        env:
        - name: DATASTORE_NAME
          value: http://datastore-svc/fetch
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: fortune
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: front
---
apiVersion: v1
kind: Pod
metadata:
  name: portal
  namespace: fortune
  labels:
    app.kubernetes.io/name: portal
spec:
  containers:
  - image: fortune-portal:dev
    name: portal
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app.kubernetes.io/name: datastore
  name: datastore
  namespace: fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datastore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datastore
    spec:
      containers:
      - image: fortune-datastore:dev
        name: datastore
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-svc
  namespace: fortune
spec:
  ports:
  - port: 80
    targetPort: 8090
  selector:
    app.kubernetes.io/name: datastore