apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: alice
  name: alice
---
apiVersion: v1
kind: Namespace
metadata:
  name: alice
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app.kubernetes.io/name: echo-server
  name: echo-server
  namespace: alice
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - image: echoserver:0.0.2
        name: echo-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: alice
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: echo-server
---
apiVersion: v1
kind: Pod
metadata:
  name: portal
  namespace: alice
  labels:
    app.kubernetes.io/name: portal
spec:
  containers:
  - image: nginx
    name: nginx
