---
apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app.kubernetes.io/name: front
  name: front
  namespace: fortune
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front
    spec:
      hostPID: true
      # hostNetwork: true
      containers:
      - image: fortune-front:dev
        name: front
        ports:
        - name: https
          containerPort: 8081
        env:
        - name: DATASTORE_NAME
          value: http://datastore-svc/fetch
        imagePullPolicy: Never
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: true
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: fortune
spec:
  ports:
  - port: 443
    name: https
    targetPort: 8081
  selector:
    app.kubernetes.io/name: front
