apiVersion: v1
kind: Pod
metadata:
  name: portal
  namespace: fortune
  labels:
    app.kubernetes.io/name: portal
spec:
  containers:
  - image: fortune-portal:dev
    name: portal
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /run/spire/sockets
      readOnly: true
  volumes:
  - name: spire-agent-socket
    hostPath:
      path: /run/spire/sockets
      type: Directory